server:
  port: 8833
spring:
  application:
    name: gwmall-unqid
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true

#logging:
#  level:
#    com:
#      tuling:
#        tulingmall:
#          feignapi:
#            ums:
#              UmsMemberReceiveAddressFeignApi: debug
